# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20170824_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_updated', '-date_created', '-pk'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('A', 'Add'), ('R', 'Remove')], default='R', max_length=1),
        ),
    ]
