# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:39
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to=authentication.models.image_upload_location),
        ),
    ]
