# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment'),
        ('authentication', '0002_auto_20170730_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(to='post.Tag'),
        ),
    ]
