# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170820_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='intro_slogan',
        ),
    ]
